/// Generates a Swift source file from a resolved configuration.
///
/// Used by the `EnvCodegenPlugin` build plugin for targets that cannot read
/// `.env` at runtime, such as an app bundle. Because the plugin declares the
/// `.env` files as build inputs, editing one correctly triggers regeneration —
/// which is the guarantee a macro reading the filesystem cannot provide.
public struct EnvSourceGenerator: Sendable {
    public struct Options: Sendable {
        /// Name of the generated enum.
        public var typeName: String

        /// Access level for the generated type and its members.
        public var accessLevel: String

        /// Scrambles values marked `# env: secret` so they do not appear in
        /// `strings` output.
        ///
        /// This is obfuscation, not protection: anyone able to run the binary
        /// can recover the value. Keys that must stay secret belong on a server,
        /// not in a shipped app.
        public var obfuscatesSecrets: Bool

        /// Emits `schema`, `generatedKeys`, and `sourceFiles` metadata.
        public var includesMetadata: Bool

        public init(
            typeName: String = "Env",
            accessLevel: String = "public",
            obfuscatesSecrets: Bool = true,
            includesMetadata: Bool = true
        ) {
            self.typeName = typeName
            self.accessLevel = accessLevel
            self.obfuscatesSecrets = obfuscatesSecrets
            self.includesMetadata = includesMetadata
        }

        public static var `default`: Options { Options() }
    }

    public enum GeneratorError: Error, Sendable, CustomStringConvertible {
        case contractRequired
        case missingRequiredValue(key: String)

        public var description: String {
            switch self {
            case .contractRequired:
                "error: code generation requires a .env.example file to declare the key contract"
            case let .missingRequiredValue(key):
                "error: no value for required key '\(key)'"
            }
        }
    }

    public var options: Options

    public init(options: Options = .default) {
        self.options = options
    }

    /// Renders the source file.
    ///
    /// - Throws: ``GeneratorError`` when there is no contract to generate from,
    ///   or a required key has no value.
    public func generate(
        from resolution: EnvResolution,
        schema: EnvSchema?
    ) throws -> String {
        guard let contract = resolution.contract else {
            throw GeneratorError.contractRequired
        }

        let access = options.accessLevel.isEmpty ? "" : options.accessLevel + " "
        var lines: [String] = []

        lines.append("// Generated by env-codegen. Do not edit; edit the .env files instead.")
        lines.append("// swift-format-ignore-file")
        lines.append("// swiftlint:disable all")
        lines.append("")
        lines.append("import Foundation")
        lines.append("")
        lines.append(contentsOf: documentationBlock(schema: schema, resolution: resolution))
        lines.append("\(access)enum \(options.typeName) {")

        var needsDeobfuscator = false

        for declaration in contract.declarations {
            let value = resolution.values[declaration.key]

            if value == nil || value?.isEmpty == true {
                guard declaration.isOptional else {
                    throw GeneratorError.missingRequiredValue(key: declaration.key)
                }
            }

            lines.append("")
            lines.append(contentsOf: memberDocumentation(declaration, indent: "    "))

            let isObfuscated =
                options.obfuscatesSecrets && declaration.isSecret
                    && declaration.type == .string && value?.isEmpty == false
            if isObfuscated { needsDeobfuscator = true }

            lines.append(
                contentsOf: member(
                    declaration,
                    value: value,
                    access: access,
                    obfuscated: isObfuscated
                )
            )
        }

        if options.includesMetadata {
            lines.append("")
            lines.append(contentsOf: metadata(contract: contract, schema: schema, access: access))
        }

        if needsDeobfuscator {
            lines.append("")
            lines.append(contentsOf: deobfuscator(access: access))
        }

        lines.append("}")
        lines.append("")

        return lines.joined(separator: "\n")
    }

    // MARK: - Sections

    private func documentationBlock(
        schema: EnvSchema?,
        resolution: EnvResolution
    ) -> [String] {
        var lines = ["/// Configuration baked in at build time."]
        lines.append("///")
        lines.append("/// Schema: `\(schema?.name ?? "none")`")
        if !resolution.loadedFiles.isEmpty {
            lines.append("///")
            lines.append("/// Resolved from, in ascending precedence:")
            for path in resolution.loadedFiles {
                lines.append("/// - `\(EnvPath.lastComponent(of: path))`")
            }
        }
        return lines
    }

    private func memberDocumentation(
        _ declaration: EnvKeyDeclaration,
        indent: String
    ) -> [String] {
        var lines: [String] = []
        for comment in declaration.documentation {
            lines.append("\(indent)/// \(comment)")
        }
        if !declaration.documentation.isEmpty {
            lines.append("\(indent)///")
        }
        lines.append("\(indent)/// Environment key: `\(declaration.key)`")
        if declaration.isSecret {
            lines.append("\(indent)///")
            lines.append(
                "\(indent)/// - Warning: Marked secret. Baked into the binary and recoverable"
            )
            lines.append("\(indent)///   by anyone who can run it.")
        }
        return lines
    }

    private func member(
        _ declaration: EnvKeyDeclaration,
        value: String?,
        access: String,
        obfuscated: Bool
    ) -> [String] {
        let name = EnvNaming.escaped(declaration.swiftName)
        let type =
            declaration.isOptional
                ? "\(declaration.type.swiftTypeName)?"
                : declaration.type.swiftTypeName

        guard let value, !value.isEmpty else {
            return ["    \(access)static let \(name): \(type) = nil"]
        }

        if obfuscated {
            let bytes = Self.obfuscate(value, salt: declaration.key)
            let literal = bytes.map(String.init).joined(separator: ", ")
            return [
                "    \(access)static var \(name): \(type) {",
                "        _deobfuscate([\(literal)], salt: \(Self.stringLiteral(declaration.key)))",
                "    }",
            ]
        }

        return ["    \(access)static let \(name): \(type) = \(literal(for: value, as: declaration.type))"]
    }

    private func metadata(
        contract: EnvContract,
        schema: EnvSchema?,
        access: String
    ) -> [String] {
        let keys = contract.declarations.map { Self.stringLiteral($0.key) }
        return [
            "    /// The schema this file was generated for.",
            "    \(access)static let schema: String = \(Self.stringLiteral(schema?.name ?? ""))",
            "",
            "    /// Every key declared by the contract, in declaration order.",
            "    \(access)static let generatedKeys: [String] = [",
            "        " + keys.joined(separator: ", "),
            "    ]",
        ]
    }

    private func deobfuscator(access _: String) -> [String] {
        [
            "    /// Reverses the build-time scrambling applied to secret values.",
            "    ///",
            "    /// Defeats `strings`, nothing more.",
            "    private static func _deobfuscate(_ bytes: [UInt8], salt: String) -> String {",
            "        let key = Array(salt.utf8)",
            "        var scalars = [UInt8]()",
            "        scalars.reserveCapacity(bytes.count)",
            "        for (offset, byte) in bytes.enumerated() {",
            "            scalars.append(byte ^ key[offset % key.count])",
            "        }",
            "        return String(decoding: scalars, as: UTF8.self)",
            "    }",
        ]
    }

    // MARK: - Literals

    /// Renders `value` as a Swift literal of `type`.
    ///
    /// Force-unwraps are safe for `URL` and `Data` because the resolver has
    /// already validated the value decodes; a mismatch fails the build before
    /// reaching here.
    private func literal(for value: String, as type: EnvValueType) -> String {
        switch type {
        case .string:
            return Self.stringLiteral(value)
        case .int, .double:
            return value.trimmingASCIIWhitespace()
        case .bool:
            let normalized = value.trimmingASCIIWhitespace().lowercased()
            return ["true", "yes", "on", "1"].contains(normalized) ? "true" : "false"
        case .url:
            return "URL(string: \(Self.stringLiteral(value.trimmingASCIIWhitespace())))!"
        case .data:
            return "Data(base64Encoded: \(Self.stringLiteral(value.trimmingASCIIWhitespace())))!"
        case .stringArray:
            let elements = value.split(separator: ",").map {
                Self.stringLiteral(String($0).trimmingASCIIWhitespace())
            }
            return "[" + elements.joined(separator: ", ") + "]"
        case .intArray:
            let elements = value.split(separator: ",").map {
                String($0).trimmingASCIIWhitespace()
            }
            return "[" + elements.joined(separator: ", ") + "]"
        }
    }

    /// Escapes `value` as a Swift string literal.
    static func stringLiteral(_ value: String) -> String {
        var escaped = "\""
        for character in value.unicodeScalars {
            switch character {
            case "\\": escaped += "\\\\"
            case "\"": escaped += "\\\""
            case "\n": escaped += "\\n"
            case "\r": escaped += "\\r"
            case "\t": escaped += "\\t"
            case "\0": escaped += "\\0"
            default:
                // Control characters have no literal spelling.
                if character.value < 0x20 || character.value == 0x7F {
                    escaped += "\\u{\(Self.hex(character.value))}"
                } else {
                    escaped.unicodeScalars.append(character)
                }
            }
        }
        return escaped + "\""
    }

    /// Uppercase hex, without a Foundation dependency for formatting.
    private static func hex(_ value: UInt32) -> String {
        let digits = Array("0123456789ABCDEF")
        var result = ""
        var remaining = value
        repeat {
            result = String(digits[Int(remaining % 16)]) + result
            remaining /= 16
        } while remaining > 0
        return result.count < 2 ? "0" + result : result
    }

    /// XORs `value` against a salt derived from the key name.
    ///
    /// Deterministic, so repeated builds of identical input produce identical
    /// output and do not defeat build caching.
    static func obfuscate(_ value: String, salt: String) -> [UInt8] {
        let key = Array(salt.utf8)
        return Array(value.utf8).enumerated().map { offset, byte in
            byte ^ key[offset % key.count]
        }
    }
}
